name: catfeina
description: "Um aplicativo para dispositivos móveis e desktop desenvolvido para amantes de poesia."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core & Infrastructure
  flutter_riverpod: ^2.5.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.6.0
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  dio: ^5.5.0+1

  # Features
  flutter_tts: ^4.0.2
  just_audio: ^0.9.38

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.1
  introduction_screen: ^3.1.14
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
