package com.marin.core.tema

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006D39)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF96F8B2)
val md_theme_light_onPrimaryContainer = Color(0xFF00210D)
val md_theme_light_secondary = Color(0xFF506352)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD3E8D3)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1F12)
val md_theme_light_tertiary = Color(0xFF3B6470)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBFE9F8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF7)
val md_theme_light_onBackground = Color(0xFF1A1C1A)
val md_theme_light_surface = Color(0xFFFCFDF7)
val md_theme_light_onSurface = Color(0xFF1A1C1A)
val md_theme_light_surfaceVariant = Color(0xFFDEE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF424941)
val md_theme_light_outline = Color(0xFF727970)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312E)
val md_theme_light_inversePrimary = Color(0xFF7BDA98)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D39)
val md_theme_light_outlineVariant = Color(0xFFC2C9BF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7BDA98)
val md_theme_dark_onPrimary = Color(0xFF00391A)
val md_theme_dark_primaryContainer = Color(0xFF005329)
val md_theme_dark_onPrimaryContainer = Color(0xFF96F8B2)
val md_theme_dark_secondary = Color(0xFFB7CCB8)
val md_theme_dark_onSecondary = Color(0xFF233426)
val md_theme_dark_secondaryContainer = Color(0xFF394B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFD3E8D3)
val md_theme_dark_tertiary = Color(0xFFA4CDDB)
val md_theme_dark_onTertiary = Color(0xFF043541)
val md_theme_dark_tertiaryContainer = Color(0xFF214C58)
val md_theme_dark_onTertiaryContainer = Color(0xFFBFE9F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1A)
val md_theme_dark_onBackground = Color(0xFFE2E3DE)
val md_theme_dark_surface = Color(0xFF1A1C1A)
val md_theme_dark_onSurface = Color(0xFFE2E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF424941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BF)
val md_theme_dark_outline = Color(0xFF8B9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1A)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DE)
val md_theme_dark_inversePrimary = Color(0xFF006D39)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7BDA98)
val md_theme_dark_outlineVariant = Color(0xFF424941)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF2B8F55)
