package com.marin.core.tema

import androidx.compose.ui.graphics.Color

// Paleta de Cores - Outono (Light)
val outono_theme_light_primary = Color(0xFF8C5100)
val outono_theme_light_onPrimary = Color(0xFFFFFFFF)
val outono_theme_light_primaryContainer = Color(0xFFFFDDBA)
val outono_theme_light_onPrimaryContainer = Color(0xFF2D1600)
val outono_theme_light_secondary = Color(0xFF735A42)
val outono_theme_light_onSecondary = Color(0xFFFFFFFF)
val outono_theme_light_secondaryContainer = Color(0xFFFFDDBA)
val outono_theme_light_onSecondaryContainer = Color(0xFF291806)
val outono_theme_light_tertiary = Color(0xFF5A633A)
val outono_theme_light_onTertiary = Color(0xFFFFFFFF)
val outono_theme_light_tertiaryContainer = Color(0xFFDEE9B4)
val outono_theme_light_onTertiaryContainer = Color(0xFF181E01)
val outono_theme_light_error = Color(0xFFBA1A1A)
val outono_theme_light_onError = Color(0xFFFFFFFF)
val outono_theme_light_errorContainer = Color(0xFFFFDAD6)
val outono_theme_light_onErrorContainer = Color(0xFF410002)
val outono_theme_light_background = Color(0xFFFFF8F6)
val outono_theme_light_onBackground = Color(0xFF211A13)
val outono_theme_light_surface = Color(0xFFFFF8F6)
val outono_theme_light_onSurface = Color(0xFF211A13)
val outono_theme_light_surfaceVariant = Color(0xFFF1E0D1)
val outono_theme_light_onSurfaceVariant = Color(0xFF50453A)
val outono_theme_light_outline = Color(0xFF827568)

// Paleta de Cores - Outono (Dark)
val outono_theme_dark_primary = Color(0xFFFFB866)
val outono_theme_dark_onPrimary = Color(0xFF4A2900)
val outono_theme_dark_primaryContainer = Color(0xFF6A3D00)
val outono_theme_dark_onPrimaryContainer = Color(0xFFFFDDBA)
val outono_theme_dark_secondary = Color(0xFFE1C1A5)
val outono_theme_dark_onSecondary = Color(0xFF402C18)
val outono_theme_dark_secondaryContainer = Color(0xFF59422C)
val outono_theme_dark_onSecondaryContainer = Color(0xFFFFDDBA)
val outono_theme_dark_tertiary = Color(0xFFC2CD9A)
val outono_theme_dark_onTertiary = Color(0xFF2C340F)
val outono_theme_dark_tertiaryContainer = Color(0xFF424B24)
val outono_theme_dark_onTertiaryContainer = Color(0xFFDEE9B4)
val outono_theme_dark_error = Color(0xFFFFB4AB)
val outono_theme_dark_onError = Color(0xFF690005)
val outono_theme_dark_errorContainer = Color(0xFF93000A)
val outono_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val outono_theme_dark_background = Color(0xFF18120C)
val outono_theme_dark_onBackground = Color(0xFFEFE0D4)
val outono_theme_dark_surface = Color(0xFF18120C)
val outono_theme_dark_onSurface = Color(0xFFEFE0D4)
val outono_theme_dark_surfaceVariant = Color(0xFF50453A)
val outono_theme_dark_onSurfaceVariant = Color(0xFFD4C4B5)
val outono_theme_dark_outline = Color(0xFF9D8E81)
