package com.marin.core.tema

import androidx.compose.ui.graphics.Color

// Paleta de Cores - Verão (Light)
val verao_theme_light_primary = Color(0xFF9C4300)
val verao_theme_light_onPrimary = Color(0xFFFFFFFF)
val verao_theme_light_primaryContainer = Color(0xFFFFDBC8)
val verao_theme_light_onPrimaryContainer = Color(0xFF331100)
val verao_theme_light_secondary = Color(0xFF765848)
val verao_theme_light_onSecondary = Color(0xFFFFFFFF)
val verao_theme_light_secondaryContainer = Color(0xFFFFDBC8)
val verao_theme_light_onSecondaryContainer = Color(0xFF2B170A)
val verao_theme_light_tertiary = Color(0xFF656031)
val verao_theme_light_onTertiary = Color(0xFFFFFFFF)
val verao_theme_light_tertiaryContainer = Color(0xFFEBE4AA)
val verao_theme_light_onTertiaryContainer = Color(0xFF1F1C00)
val verao_theme_light_error = Color(0xFFBA1A1A)
val verao_theme_light_onError = Color(0xFFFFFFFF)
val verao_theme_light_errorContainer = Color(0xFFFFDAD6)
val verao_theme_light_onErrorContainer = Color(0xFF410002)
val verao_theme_light_background = Color(0xFFFFF8F6)
val verao_theme_light_onBackground = Color(0xFF221A15)
val verao_theme_light_surface = Color(0xFFFFF8F6)
val verao_theme_light_onSurface = Color(0xFF221A15)
val verao_theme_light_surfaceVariant = Color(0xFFF4DED4)
val verao_theme_light_onSurfaceVariant = Color(0xFF52443C)
val verao_theme_light_outline = Color(0xFF85736B)

// Paleta de Cores - Verão (Dark)
val verao_theme_dark_primary = Color(0xFFFFB68E)
val verao_theme_dark_onPrimary = Color(0xFF542100)
val verao_theme_dark_primaryContainer = Color(0xFF783200)
val verao_theme_dark_onPrimaryContainer = Color(0xFFFFDBC8)
val verao_theme_dark_secondary = Color(0xFFE6BEAB)
val verao_theme_dark_onSecondary = Color(0xFF432B1D)
val verao_theme_dark_secondaryContainer = Color(0xFF5C4132)
val verao_theme_dark_onSecondaryContainer = Color(0xFFFFDBC8)
val verao_theme_dark_tertiary = Color(0xFFCFC890)
val verao_theme_dark_onTertiary = Color(0xFF353107)
val verao_theme_dark_tertiaryContainer = Color(0xFF4C481C)
val verao_theme_dark_onTertiaryContainer = Color(0xFFEBE4AA)
val verao_theme_dark_error = Color(0xFFFFB4AB)
val verao_theme_dark_onError = Color(0xFF690005)
val verao_theme_dark_errorContainer = Color(0xFF93000A)
val verao_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val verao_theme_dark_background = Color(0xFF19120F)
val verao_theme_dark_onBackground = Color(0xFFF0DFD8)
val verao_theme_dark_surface = Color(0xFF19120F)
val verao_theme_dark_onSurface = Color(0xFFF0DFD8)
val verao_theme_dark_surfaceVariant = Color(0xFF52443C)
val verao_theme_dark_onSurfaceVariant = Color(0xFFD7C2B9)
val verao_theme_dark_outline = Color(0xFFA08D84)
