name: Reportar um Bug no Catfeina
description: Encontrou algo que não está funcionando como deveria no aplicativo Catfeina?
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por ajudar a melhorar o Catfeina!
        Antes de reportar, por favor, verifique se já não existe uma issue similar aberta.
  - type: textarea
    attributes:
      label: Descreva o Bug
      description: O que aconteceu e o que você esperava que acontecesse?
      placeholder: |
        Ex: Ao clicar no botão 'Favoritar', o aplicativo fecha inesperadamente. Eu esperava que o poema fosse salvo como favorito.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Passos para Reproduzir
      description: Como podemos reproduzir o problema?
      placeholder: |
        1. Abra o aplicativo.
        2. Navegue para a tela de uma poesia.
        3. Clique no ícone de coração (Favoritar).
        4. O app fecha.
    validations:
      required: true
  - type: input
    attributes:
      label: Versão do Catfeina
      description: Se você souber a versão do aplicativo, informe aqui.
      placeholder: Ex. v1.0.0
    validations:
      required: false
  - type: textarea
    attributes:
      label: Logs ou Mensagens de Erro (se houver)
      description: Copie e cole quaisquer logs relevantes. Isso é extremamente útil!
      render: console
      placeholder: |
        [Cole os logs aqui]
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
        ### **Ambiente de Execução**
  - type: dropdown
    attributes:
      label: Plataforma
      description: Em qual plataforma o bug aconteceu?
      options:
        - Android
        - Desktop
        - iOS
        - Web
    validations:
      required: true
  - type: input
    attributes:
      label: Sistema Operacional e Versão
      description: Qual SO e versão? (E modelo do aparelho, se for Android)
      placeholder:
        Ex: Android 14 (Pixel 7), Windows 11, macOS Sonoma, Ubuntu 22.04
    validations:
      required: true
