name: Catfeina CI

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_lint:
    name: "Build & Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # Action oficial para cache e setup do Gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # O comando 'build' já compila e executa tarefas básicas de verificação.
      # Como não há uma suíte de testes, este é o nosso principal passo de validação.
      - name: Build project
        run: ./gradlew build
