# .github/workflows/coverage.yml
name: Test Coverage with Coveralls

permissions:
  contents: read

on:pull_request:
  branches: [ main ]
  push:
    branches: [ main ]

jobs:
  coverage:
    name: "Calculate Test Coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests and generate coverage report
        # Esta tarefa é habilitada pelo plugin Jacoco e executa os testes, gerando o relatório.
        run: ./gradlew testDebugUnitTestCoverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          # O token é pego automaticamente para repositórios públicos.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Especifica o caminho para o relatório XML gerado pelo Jacoco.
          path-to-lcov: ${{ github.workspace }}/app/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml

